name: ci
on:
  push:
    branches: main
  pull_request:
  workflow_dispatch:

jobs:
  build-iso:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:

    - name: Install Package
      run: sudo apt-get update && sudo apt-get install -y simple-cdd
    - name: Build ISO
      run: build-simple-cdd
    - run: ls
